### ISSUE TITLE
[formatter.c++] is not supported

### ISSUE THREAD

**Issue by zimbatm** [numtide/treefmt#124]
**Describe the bug**

treefmt is not able to parse this treefmt.toml:
```
[formatter.c++]
command = "clang-format"
# ....
```

**Expected behavior**

Nix seems to parse that construct properly.
```
nix-repl> :p builtins.fromTOML("[formatter.c++]\nfoo=3")
{ formatter = { "c++" = { foo = 3; }; }; }
```
It might be a bug in the TOML parser library that we use.

**Comment by basile-henry** [comment]
I think the `toml` parser library we use is correct and `nix`'s one is more/too relaxed.

From the [`toml` spec](https://toml.io/en/v1.0.0#keys):

> A key may be either bare, quoted, or dotted.
>
> Bare keys may only contain ASCII letters, ASCII digits, underscores, and dashes (A-Za-z0-9_-).

So you need to quote `c++`: `[formatter."c++"]`

**Comment by zimbatm** [comment]
/cc @teh^ 

In that case this issue can be closed, thanks!
