### ISSUE TITLE
treefmt cli: allow explicitly specifying a specific formatter

### ISSUE THREAD

**Issue by flokli** [numtide/treefmt#167]
Sometimes `treefmt` with a bunch of formatters is a bit slow. In some cases, I'd like to explicitly narrow down the list of formatters to run.

It'd be nice if I could only run a subset of formatters, by invoking `treefmt -f nix,terraform` (or similar syntax)

**Comment by zimbatm** [comment]
I like this. :+1:

**Comment by brianmcgee** [comment]
@zimbatm should this issue be closed as it looks like it was already merged?

**Comment by zimbatm** [comment]
thanks
