### ISSUE TITLE
Add `--project-root-file` option

### ISSUE THREAD

**Issue by zimbatm** [numtide/treefmt#191]
**Is your feature request related to a problem? Please describe.**

When the `--config-file` is passed, treefmt doesn't know how to find the project root anymore. We can pass the `--project-root` option, but that leads to wrappers like this: https://github.com/numtide/treefmt-nix/blob/11c31677c45957fb1de0a9102912cf6462730884/module-options.nix#L97-L115

**Describe the solution you'd like**

Add a `--project-root-file <filename>` option that will search up the filesystem, starting from $PWD for the given "filename".

The filename is a relative path and can contain `/` in it. Eg: `--project-root-file .git/config` can be used to point to a git repo root.

**Describe alternatives you've considered**

Embed even more project root finding logic into the project?

**Additional context**

**Comment by brianmcgee** [comment]
Probably best to wait and implement this after #194 and #195.
