### ISSUE TITLE
Migrate from structop to clap

### ISSUE THREAD

**Issue by brianmcgee** [numtide/treefmt#194]
[structopt](https://docs.rs/structopt/latest/structopt/) is now in maintenance mode:

> As clap v3 is now out, and the structopt features are integrated into (almost as-is), structopt is now in maintenance mode: no new feature will be added.

It looks like a migration to clap is almost like for like, with only a few minor changes to things like the `-v` arg definition. For the most part though it looks to use the same macros and signatures.

I would recommend increasing the test coverage for the cli parsing first before making the swap in order to catch any nuanced bugs that might get introduced.

**Comment by brianmcgee** [comment]
I think it makes sense for you to continue with this issue @aldoborrero as you already have a [branch in progress](https://github.com/numtide/treefmt/tree/feat/migrate-to-clap)

**Comment by zimbatm** [comment]
Good to know, it would make sense indeed.
