### ISSUE TITLE
Binary for x64 Linux fails to run

### ISSUE THREAD

**Issue by renoire** [numtide/treefmt#205]
Steps I took:

1. I downloaded the binary for unknown Linux x64 and made sure that the check sum matches. 
2. I unpacked the tar.gz and checked that the file has execution permissions.
3. I run ./treefmt and get:
bash: ./treefmt: cannot execute binary file: Exec format error

I'm on Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz / Ubuntu 22.04

**Comment by zimbatm** [comment]
Thanks, can you give me the output of `uname -a`?

**Comment by renoire** [comment]
> 

Linux renoire-ThinkPad-P50 5.15.0-56-generic #62-Ubuntu SMP Tue Nov 22 19:54:14 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Comment by zimbatm** [comment]
Thanks, can you give me the exact name of the file downloaded from https://github.com/numtide/treefmt/releases/tag/v0.5.0 ?

**Comment by renoire** [comment]
Well, I downloaded the wrong file by mistake :)
