### ISSUE TITLE
Cannot use statix to format code with treefmt 

### ISSUE THREAD

**Issue by kaikikokuke** [numtide/treefmt#241]
First of all thanks to everyone here. This project is really useful for me, and I really appreciate it.

I want to format my files using **statix**. As I understood correctly, the syntax should be compatible (<command> [options] [...<files>]
), as 

`~> statix fix flake.nix`

works.

However, using this toml file:
```
# One CLI to format the code tree - https://github.com/numtide/treefmt

[formatter.mylanguage]
# Formatter to run
command = statix"
# Command-line arguments for the command
options = ["fix"]
# Glob pattern of files to include
includes = [ "*.nix" ]
# Glob patterns of files to exclude
excludes = []
```
and running `treefmt` i get an error message:

```
-> nix run nixpkgs#treefmt -- 
[WARN]: cache: failed to load the manifest due to: No such file or directory (os error 2)
[INFO]: Error using formatter #mylanguage:
• [STDOUT]:

• [STDERR]:
error: Found argument '/home/user/home-manager/home.nix' which wasn't expected, or isn't valid in this context

USAGE:
    statix fix [OPTIONS] [--] [TARGET]

For more information try --help

[ERR]: #mylanguage's formatter failed: exit status 2

```

I think, that somehow the file path is not passed to `statix` after the `fix` subcommand.

**To Reproduce**

1. `treefmt --init `and create a **toml** file
2. change formatter command in toml to `"statix"`
3. change options to `["fix"]`
4. change includes to `["*.nix"]`
5. run `treefmt`

**Expected behavior**

I expected the files to be formatted using statix.

**System information**

System: x86_64-linux
Fedora: 37
Kernel Version: 6.3.8-100.fc37.x86_64
treefmt version: 0.5.0

**Comment by zimbatm** [comment]
I had a quick look and it seems like statix only supports a single file as an argument, whereas treefmt assumes that it can pass all of the matched files in a single process call.

The full spec is over here: https://numtide.github.io/treefmt/formatters-spec/

A common workaround is to use a bash wrapper like this:
```toml
[formatter.statix]
command = "bash"
options = ["-euc" "for file in \"$@\"; do statix fix \"$file\"; done"]
```

It's not super fast, but it should work. I would also recommend reporting the issue upstream.

**Comment by kaikikokuke** [comment]
Yes that works. Thanks for the helpful reply. I will open up an issue upstream.
