### ISSUE TITLE
Confusing documentation about `includes` options

### ISSUE THREAD

**Issue by pinage404** [numtide/treefmt#242]
**Describe the bug**

Hi, i'm new user
i've discovered the project and i'm reading the documentation

The configuration describes the `includes` property as a regex
https://github.com/numtide/treefmt/blob/8ca89b1bb3823219a4d407df7e8bedda283e8f1c/docs/treefmt-configuration.md?plain=1#L13

But few lines down, it is described as a glob pattern
https://github.com/numtide/treefmt/blob/8ca89b1bb3823219a4d407df7e8bedda283e8f1c/docs/treefmt-configuration.md?plain=1#L35

**Expected behavior**

Is it a regex OR a glob pattern ?

I would like the documentation to be consistent

**Comment by zimbatm** [comment]
thanks. The includes and excludes use the glob patterns, not regex.
