### ISSUE TITLE
Unexpected behaviour of `tree_root`

### ISSUE THREAD

**Issue by KAction** [numtide/treefmt#264]
According to [comment in the source](https://github.com/numtide/treefmt/blob/main/src/command/mod.rs#L72), `tree_root` is the directory where `treefmt.toml` is located. 

In reality, `tree_root`, unless overridden by environment variable, defaults to the current variable, resulting in potentially different formatter's behavior depending on from which directory `treefmt` is run. Also, since `work_dir` of formatters is derived from `tree_root`,
running `treefmt` in different sub-directory of the project busts the cache completely.

Is it actually a bug (I can make PR), or is the comment is misleading and things work as they should?

**Comment by brianmcgee** [comment]
I don't believe this is an issue in v2.
