### ISSUE TITLE
Multiple formatters when using --stdin

### ISSUE THREAD

**Issue by terlar** [numtide/treefmt#274]
**Is your feature request related to a problem? Please describe.**

I configured the formatter `dos2unix` which I essentially applied to all files in the project, then everything seemed to work fine, however in my editor I utilize `treefmt --stdin FILENAME < BUFFER` in order to have consistent formatting across the project without duplicate configuration. Recently I noticed the formatting stopped working and when I debugged this I got this:
```
$ treefmt --stdin test.nix < test.nix
[WARN ] multiple formatters matched the path. picking the first one
{a = 1; b = 2; c = 3;}
```

So it didn't format the file because `dos2unix` was the first one.

**Describe the solution you'd like**

Either a way to select which formatter has priority in this case, or I guess the best case would be to run all the formatters, just like it does when you apply via `treefmt test.nix`.

**Describe alternatives you've considered**

- Not have multiple formatters touching the same files.
- Format file directly via argument, however my editor formatter relies on stdin/stdout formatting.

**Comment by terlar** [comment]
@brianmcgee I see the new release with golang rewrite is around the corner. Will this be fixed in the new version?

**Comment by brianmcgee** [comment]
@terlar, if you have an example config you can share, I'd be happy to add it to the tests to ensure we cover this specifically.

**Comment by terlar** [comment]
I just tested this on the main branch and it seems the `--stdin` feature is broken or it works differently than before. It does not format from stdin, but instead tries to use stdin as the filenames or format the file provided as filename (used to figure out which formatter to use).

```sh
$ cat temp-test/treefmt.toml
# One CLI to format the code tree - https://git.numtide.com/numtide/treefmt
[formatter.dos2unix]
command = "dos2unix"
includes = ["*.yaml"]
options = ["--keepdate"]

[formatter.yamlfmt]
command = "yamlfmt"
includes = ["*.yaml"]⏎                                                                           $ cat --show-ends temp-test/dos2unix+yaml.yaml
hello: world^M$
^M$
list:^M$
  - one^M$
  - two^M$
      - three^M$
$ cat temp-test/dos2unix+yaml.yaml | nix shell nixpkgs#dos2unix nixpkgs#yamlfmt --command nix run
 . -- -C temp-test --stdin sample.yaml
treefmt: error: failed to generate change set: failed to walk path: lstat /home/terje/src/github.com/numtide/treefmt/temp-test/sample.yaml: no such file or directory
```

**Comment by brianmcgee** [comment]
@terlar seems I misunderstood how this was supposed to work as I was porting things to Go. I'll review the functionality more closely and bring 2.x inline. I've created https://github.com/numtide/treefmt/issues/310

**Comment by brianmcgee** [comment]
@terlar https://github.com/numtide/treefmt/pull/313 was merged, give main another go whenever you have a chance. 

```
❯ cat test.toml 
# One CLI to format the code tree - https://git.numtide.com/numtide/treefmt
[formatter.dos2unix]
command = "dos2unix"
includes = ["*.yaml"]
options = ["--keepdate"]

[formatter.yamlfmt]
command = "yamlfmt"
includes = ["*.yaml"]%  

❯ cat --show-ends dos2unix+yaml.yaml
hello: world^M$
^M$
list:^M$
  - one^M$
  - two^M$
      - three^M$

❯ cat dos2unix+yaml.yaml | nix run .# -- --config-file test.toml --stdin sample.yaml
hello: world
list:
  - one
  - two - three
   
❯ cat dos2unix+yaml.yaml | nix run .# -- --config-file test.toml --stdin sample.yaml -v
INFO format | dos2unix: 1 files processed in 899.52µs
INFO format | yamlfmt: 1 files processed in 2.720321ms
hello: world
list:
  - one
  - two - three

```

Formatters are applied first in `priority` order (lower the number, higher the precedence) with the default being `0`, and then in lexicographical order.

**Comment by terlar** [comment]
Thank you! Looks promising, I will have a look soon.

**Comment by terlar** [comment]
Yes, I can confirm this now works. So I will close this issue.
