### ISSUE TITLE
gofmt should not format vendor directories

### ISSUE THREAD

**Issue by tom-wegener** [numtide/treefmt#306]
**Is your feature request related to a problem? Please describe.**

When using gofmt it always also formats my vendor directory which is not necessary since this is code I won't touch.

It also completely ignores any exclude settings but I guess that this is a gofmt problem since it does not support excludes.

**Describe the solution you'd like**

The trick most people use is something like gofmt -w `go list ./... | grep -v /vendor/` which is not perfect but a solid start. Similar behaviour could be switched on via the config.

**Additional context**

gofumpt also does not work.

**Comment by zimbatm** [comment]
Did you try using the `excludes` functionality?
