### ISSUE TITLE
duck-duck-go reports treefmt is $99 to buy

### ISSUE THREAD

**Issue by noonio** [numtide/treefmt#352]
If you search duckduckgo for treefmit, you get this preview

![image](https://github.com/user-attachments/assets/b97124c0-286a-4798-aa1b-88115a318dc9)

amusingly, $99 is indeed in the source-code of the website, but hidden, I suppose, by some css.

**Comment by brianmcgee** [comment]
huh...

@zimbatm this seems to be in the project page of the Numtide site. Can you have a look as my login isn't working? 

![Screenshot from 2024-07-18 17-42-05](https://github.com/user-attachments/assets/bc081255-bedc-4f18-ba72-3234762a6aee)

It might be part of the theme.

**Comment by zimbatm** [comment]
Thanks for noticing and reporting @noonio!

This was part of the website theme I bought indeed. The fix should be deployed pretty soon.
