### ISSUE TITLE
Question: Should treefmt specify a timeout when trying to open its boltdb cache?

### ISSUE THREAD

**Issue by jfly** [numtide/treefmt#408]
While debugging https://github.com/numtide/treefmt/issues/406, I found that if you have one treefmt process hung, the *next* treefmt process you start up will get hung [on this call to `bolt.Open`](https://github.com/numtide/treefmt/blob/v2.0.5/cache/cache.go#L61). This behavior is documented by [bbolt](https://github.com/etcd-io/bbolt?tab=readme-ov-file#opening-a-database):

> Please note that Bolt obtains a file lock on the data file so multiple
> processes cannot open the same database at the same time. Opening an already
> open Bolt database will cause it to hang until the other process closes it. To
> prevent an indefinite wait you can pass a timeout option to the Open()
> function:
>
> ```
> db, err := bolt.Open("my.db", 0600, &bolt.Options{Timeout: 1 * time.Second})
> ````

Should treefmt specify a timeout here? Ideally treefmt would never hang, but it feels especially unfortunate that if it does hang, it'll cause *other* treefmt processes to hang.

**Comment by brianmcgee** [comment]
Completely agree #409

**Comment by jfly** [comment]
Closing, as @brianmcgee added a timeout in https://github.com/numtide/treefmt/pull/409. Thanks!
