### ISSUE TITLE
Turn off default warning on missing formatters

### ISSUE THREAD

**Issue by zimbatm** [numtide/treefmt#496]
**Is your feature request related to a problem? Please describe.**

The goal of warning users about missing formatters was to encourage them to increase the formatting coverage on all the files of the repo.

In practice, users are now adding these files to the global ignore list (even in treefmt-nix).

This is causing unnecessary churn and toil to the users.

**Describe the solution you'd like**

Maybe a better option would be to move those warnings behind a flag. So the user can easily `treefmt --show-missing-formatters` to get the list.

**Describe alternatives you've considered**

**Additional context**

**Comment by mightyiam** [comment]
I like these warnings. Ideally, I'd be able to make them into errors, though.

**Comment by zimbatm** [comment]
Turns out everything is supported already. It just needs to be better documented.

The user can already turn down the verbosity of that message using `on-unmatched = "debug"` in their `treefmt.toml` or with `--on-unmatched=debug` on the CLI.

And if the user wants to enforce this, use `--on-unmatched=fatal` (it only prints the first entry though).

**Comment by brianmcgee** [comment]
> Turns out everything is supported already. It just needs to be better documented.

Happy to review a docs PR :wink:
